[package]
name = "ml_filtered_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.2"
#anyhow = "1.0.102"   # error handling
#crossbeam = "0.8.4"  # channels (simpler than std)
#image = "0.25.10"    # basic image processing
#reqwest = "0.13.2"   # HTTP fetching

[[bench]]
name = "pipeline"
harness = false