[build]
rustc-wrapper = "sccache"
rustc-workspace-wrapper = ""

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "linker=lld-link", "-C", "link-arg=/STACK:8388608"]

[alias]
player-xtask = "run --package hfm-player-xtask --"
