[package]
name = "hfm-web"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
chromiumoxide = { workspace = true, features = ["rustls", "fetcher", "zip8"] }
encase = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
glam = { workspace = true, features = ["std", "bytemuck", "encase"] }
image = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true, features = [
    "download-binaries",
    "copy-dylibs",
    "tls-native",
    "std",
    "ndarray",
    "directml"
] }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
remove_dir_all = { workspace = true }
renderdoc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "io-util",
    "signal"
] }
tokenizers = { workspace = true, features = ["onig"] }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { workspace = true, features = ["dx12", "wgsl"] }
winit = { workspace = true, features = ["rwh_06"] }

[target.'cfg(target_vendor = "apple")'.dependencies]
wgpu = { workspace = true, features = ["metal", "wgsl"] }
winit = { workspace = true, features = ["rwh_06"] }

[target.'cfg(all(not(target_os = "windows"), not(target_vendor = "apple")))'.dependencies]
wgpu = { workspace = true, features = ["vulkan", "wgsl"] }
winit = { workspace = true, features = ["x11", "wayland", "rwh_06"] }

[dev-dependencies]
criterion = { workspace = true }
flamegraph = { workspace = true }
