[package]
name = "hfm-web"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
chromiumoxide = { workspace = true, features = ["rustls", "fetcher", "zip8"] }
encase = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
glam = { workspace = true, features = ["std", "bytemuck", "encase"] }
image = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true, features = ["directml"] }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
remove_dir_all = { workspace = true }
renderdoc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "io-util",
    "signal"
] }
tokenizers = { workspace = true, features = ["onig"] }
wgpu = { workspace = true, features = ["dx12", "wgsl"] }
winit = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
flamegraph = { workspace = true }
